[build]
builder = "nixpacks"
buildCommand = "cd backend && python3 -m pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && python3 production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/backend"
NODE_ENV = "production"
