[build]
builder = "dockerfile"

[deploy]
startCommand = "python api_server_db.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PYTHONPATH = "/app/backend"
NODE_ENV = "production"
PORT = { default = "8000" }
