[build]
builder = "nixpacks"

[deploy]
startCommand = "python api_server_db.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# CORS Origins - Your Vercel domains
CORS_ORIGINS = { default = "https://ai-text-analysis-platform.vercel.app,https://ai-text-analysis-platform-git-main.vercel.app" }
