[build]
builder = "nixpacks"

[deploy]
startCommand = "python unified_production_server.py"
healthcheckPath = "/production/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
# Application Configuration
APP_ENV = { default = "production" }
DEBUG = { default = "false" }

# CORS Origins - Your Vercel domains
CORS_ORIGINS = { default = "https://ai-text-analysis-platform.vercel.app,https://ai-text-analysis-platform-git-main.vercel.app,https://wordcloud-six-eta.vercel.app" }

# Upload Configuration
UPLOAD_DIR = { default = "/app/uploads" }
MAX_FILE_SIZE = { default = "104857600" }  # 100MB in bytes
