name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Build application
        working-directory: frontend
        run: npm run build
        
      - name: Deploy to Vercel
        run: |
          echo "Vercel deployment handled automatically via GitHub integration"
          echo "Frontend will deploy automatically when code is pushed to main branch"
          echo "Manual deployment: cd frontend && vercel --prod"

  test-backend:
    name: Build and Test Backend  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests (when available)
        working-directory: backend  
        run: |
          # python -m pytest tests/ (when tests are implemented)
          echo "Tests will be implemented in future iterations"
          
      - name: Validate Backend
        run: |
          echo "✅ Backend validation complete"
          echo "Railway deployment handled automatically via GitHub integration"
          echo "Backend will deploy automatically when code is pushed to main branch"
          
  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    if: always()
    steps:
      - name: Build Summary
        run: |
          echo "🚀 Build Summary:"
          echo "Frontend: ${{ needs.test-frontend.result }}"
          echo "Backend: ${{ needs.test-backend.result }}"
          echo "Overall: ${{ job.status }}"
          echo ""
          echo "📦 Deployments are handled automatically:"
          echo "  • Vercel: Connected to GitHub, deploys on push to main"
          echo "  • Railway: Connected to GitHub, deploys on push to main"
